
create_clock -name clk -period 2 -waveform {0 1} [get_ports clk]
set_input_transition -rise -min 1 -clock clk [get_ports clk]
set_input_transition -fall -min 1 -clock clk [get_ports clk]
set_input_transition -rise -max 1 -clock clk [get_ports clk]
set_input_transition -fall -max 1 -clock clk [get_ports clk]
set_input_delay  -min -rise 1 -clock clk [get_ports clk]
set_input_delay  -min -fall 1 -clock clk [get_ports clk]
set_input_delay  -max -rise 1 -clock clk [get_ports clk]
set_input_delay  -max -fall 1 -clock clk [get_ports clk]
set_input_delay -clock  clk -min -rise  0.5 [get_ports resetn]
set_input_delay -clock  clk -min -fall  0.5 [get_ports resetn]
set_input_delay -clock  clk -max -rise  1 [get_ports resetn]
set_input_delay -clock  clk -max -fall  1 [get_ports resetn]
set_input_transition -clock  clk -min -rise  0.5 [get_ports resetn]
set_input_transition -clock  clk -min -fall  0.5 [get_ports resetn]
set_input_transition -clock  clk -max -rise  1 [get_ports resetn]
set_input_transition -clock  clk -max -fall  1 [get_ports resetn]
set_input_delay -clock  clk -min -rise  0.5 [get_ports mem_ready]
set_input_delay -clock  clk -min -fall  0.5 [get_ports mem_ready]
set_input_delay -clock  clk -max -rise  1 [get_ports mem_ready]
set_input_delay -clock  clk -max -fall  1 [get_ports mem_ready]
set_input_transition -clock  clk -min -rise  0.5 [get_ports mem_ready]
set_input_transition -clock  clk -min -fall  0.5 [get_ports mem_ready]
set_input_transition -clock  clk -max -rise  1 [get_ports mem_ready]
set_input_transition -clock  clk -max -fall  1 [get_ports mem_ready]
set_input_delay -clock  clk -min -rise  0.5 [get_ports mem_rdata*]
set_input_delay -clock  clk -min -fall  0.5 [get_ports mem_rdata*]
set_input_delay -clock  clk -max -rise  1 [get_ports mem_rdata*]
set_input_delay -clock  clk -max -fall  1 [get_ports mem_rdata*]
set_input_transition -clock  clk -min -rise  0.5 [get_ports mem_rdata*]
set_input_transition -clock  clk -min -fall  0.5 [get_ports mem_rdata*]
set_input_transition -clock  clk -max -rise  1 [get_ports mem_rdata*]
set_input_transition -clock  clk -max -fall  1 [get_ports mem_rdata*]
set_input_delay -clock  clk -min -rise  0.5 [get_ports pcpi_wr]
set_input_delay -clock  clk -min -fall  0.5 [get_ports pcpi_wr]
set_input_delay -clock  clk -max -rise  1 [get_ports pcpi_wr]
set_input_delay -clock  clk -max -fall  1 [get_ports pcpi_wr]
set_input_transition -clock  clk -min -rise  0.5 [get_ports pcpi_wr]
set_input_transition -clock  clk -min -fall  0.5 [get_ports pcpi_wr]
set_input_transition -clock  clk -max -rise  1 [get_ports pcpi_wr]
set_input_transition -clock  clk -max -fall  1 [get_ports pcpi_wr]
set_input_delay -clock  clk -min -rise  0.5 [get_ports pcpi_rd*]
set_input_delay -clock  clk -min -fall  0.5 [get_ports pcpi_rd*]
set_input_delay -clock  clk -max -rise  1 [get_ports pcpi_rd*]
set_input_delay -clock  clk -max -fall  1 [get_ports pcpi_rd*]
set_input_transition -clock  clk -min -rise  0.5 [get_ports pcpi_rd*]
set_input_transition -clock  clk -min -fall  0.5 [get_ports pcpi_rd*]
set_input_transition -clock  clk -max -rise  1 [get_ports pcpi_rd*]
set_input_transition -clock  clk -max -fall  1 [get_ports pcpi_rd*]
set_input_delay -clock  clk -min -rise  0.5 [get_ports pcpi_wait]
set_input_delay -clock  clk -min -fall  0.5 [get_ports pcpi_wait]
set_input_delay -clock  clk -max -rise  1 [get_ports pcpi_wait]
set_input_delay -clock  clk -max -fall  1 [get_ports pcpi_wait]
set_input_transition -clock  clk -min -rise  0.5 [get_ports pcpi_wait]
set_input_transition -clock  clk -min -fall  0.5 [get_ports pcpi_wait]
set_input_transition -clock  clk -max -rise  1 [get_ports pcpi_wait]
set_input_transition -clock  clk -max -fall  1 [get_ports pcpi_wait]
set_input_delay -clock  clk -min -rise  0.5 [get_ports pcpi_ready]
set_input_delay -clock  clk -min -fall  0.5 [get_ports pcpi_ready]
set_input_delay -clock  clk -max -rise  1 [get_ports pcpi_ready]
set_input_delay -clock  clk -max -fall  1 [get_ports pcpi_ready]
set_input_transition -clock  clk -min -rise  0.5 [get_ports pcpi_ready]
set_input_transition -clock  clk -min -fall  0.5 [get_ports pcpi_ready]
set_input_transition -clock  clk -max -rise  1 [get_ports pcpi_ready]
set_input_transition -clock  clk -max -fall  1 [get_ports pcpi_ready]
set_input_delay -clock  clk -min -rise  0.5 [get_ports irq*]
set_input_delay -clock  clk -min -fall  0.5 [get_ports irq*]
set_input_delay -clock  clk -max -rise  1 [get_ports irq*]
set_input_delay -clock  clk -max -fall  1 [get_ports irq*]
set_input_transition -clock  clk -min -rise  0.5 [get_ports irq*]
set_input_transition -clock  clk -min -fall  0.5 [get_ports irq*]
set_input_transition -clock  clk -max -rise  1 [get_ports irq*]
set_input_transition -clock  clk -max -fall  1 [get_ports irq*]
set_output_delay -clock  clk -min -rise  0.5 [get_ports trap]
set_output_delay -clock  clk -min -fall  0.5 [get_ports trap]
set_output_delay -clock  clk -max -rise  1 [get_ports trap]
set_output_delay -clock  clk -max -fall  1 [get_ports trap]
set_load 1 [get_ports trap]
set_output_delay -clock  clk -min -rise  0.5 [get_ports mem_valid]
set_output_delay -clock  clk -min -fall  0.5 [get_ports mem_valid]
set_output_delay -clock  clk -max -rise  1 [get_ports mem_valid]
set_output_delay -clock  clk -max -fall  1 [get_ports mem_valid]
set_load 1 [get_ports mem_valid]
set_output_delay -clock  clk -min -rise  0.5 [get_ports mem_instr]
set_output_delay -clock  clk -min -fall  0.5 [get_ports mem_instr]
set_output_delay -clock  clk -max -rise  1 [get_ports mem_instr]
set_output_delay -clock  clk -max -fall  1 [get_ports mem_instr]
set_load 1 [get_ports mem_instr]
set_output_delay -clock  clk -min -rise  0.5 [get_ports mem_addr*]
set_output_delay -clock  clk -min -fall  0.5 [get_ports mem_addr*]
set_output_delay -clock  clk -max -rise  1 [get_ports mem_addr*]
set_output_delay -clock  clk -max -fall  1 [get_ports mem_addr*]
set_load 1 [get_ports mem_addr*]
set_output_delay -clock  clk -min -rise  0.5 [get_ports mem_wdata*]
set_output_delay -clock  clk -min -fall  0.5 [get_ports mem_wdata*]
set_output_delay -clock  clk -max -rise  1 [get_ports mem_wdata*]
set_output_delay -clock  clk -max -fall  1 [get_ports mem_wdata*]
set_load 1 [get_ports mem_wdata*]
set_output_delay -clock  clk -min -rise  0.5 [get_ports mem_wstrb*]
set_output_delay -clock  clk -min -fall  0.5 [get_ports mem_wstrb*]
set_output_delay -clock  clk -max -rise  1 [get_ports mem_wstrb*]
set_output_delay -clock  clk -max -fall  1 [get_ports mem_wstrb*]
set_load 1 [get_ports mem_wstrb*]
set_output_delay -clock  clk -min -rise  0.5 [get_ports mem_la_read]
set_output_delay -clock  clk -min -fall  0.5 [get_ports mem_la_read]
set_output_delay -clock  clk -max -rise  1 [get_ports mem_la_read]
set_output_delay -clock  clk -max -fall  1 [get_ports mem_la_read]
set_load 1 [get_ports mem_la_read]
set_output_delay -clock  clk -min -rise  0.5 [get_ports mem_la_write]
set_output_delay -clock  clk -min -fall  0.5 [get_ports mem_la_write]
set_output_delay -clock  clk -max -rise  1 [get_ports mem_la_write]
set_output_delay -clock  clk -max -fall  1 [get_ports mem_la_write]
set_load 1 [get_ports mem_la_write]
set_output_delay -clock  clk -min -rise  0.5 [get_ports mem_la_addr*]
set_output_delay -clock  clk -min -fall  0.5 [get_ports mem_la_addr*]
set_output_delay -clock  clk -max -rise  1 [get_ports mem_la_addr*]
set_output_delay -clock  clk -max -fall  1 [get_ports mem_la_addr*]
set_load 1 [get_ports mem_la_addr*]
set_output_delay -clock  clk -min -rise  0.5 [get_ports mem_la_wdata*]
set_output_delay -clock  clk -min -fall  0.5 [get_ports mem_la_wdata*]
set_output_delay -clock  clk -max -rise  1 [get_ports mem_la_wdata*]
set_output_delay -clock  clk -max -fall  1 [get_ports mem_la_wdata*]
set_load 1 [get_ports mem_la_wdata*]
set_output_delay -clock  clk -min -rise  0.5 [get_ports mem_la_wstrb*]
set_output_delay -clock  clk -min -fall  0.5 [get_ports mem_la_wstrb*]
set_output_delay -clock  clk -max -rise  1 [get_ports mem_la_wstrb*]
set_output_delay -clock  clk -max -fall  1 [get_ports mem_la_wstrb*]
set_load 1 [get_ports mem_la_wstrb*]
set_output_delay -clock  clk -min -rise  0.5 [get_ports pcpi_valid]
set_output_delay -clock  clk -min -fall  0.5 [get_ports pcpi_valid]
set_output_delay -clock  clk -max -rise  1 [get_ports pcpi_valid]
set_output_delay -clock  clk -max -fall  1 [get_ports pcpi_valid]
set_load 1 [get_ports pcpi_valid]
set_output_delay -clock  clk -min -rise  0.5 [get_ports pcpi_insn*]
set_output_delay -clock  clk -min -fall  0.5 [get_ports pcpi_insn*]
set_output_delay -clock  clk -max -rise  1 [get_ports pcpi_insn*]
set_output_delay -clock  clk -max -fall  1 [get_ports pcpi_insn*]
set_load 1 [get_ports pcpi_insn*]
set_output_delay -clock  clk -min -rise  0.5 [get_ports pcpi_rs1*]
set_output_delay -clock  clk -min -fall  0.5 [get_ports pcpi_rs1*]
set_output_delay -clock  clk -max -rise  1 [get_ports pcpi_rs1*]
set_output_delay -clock  clk -max -fall  1 [get_ports pcpi_rs1*]
set_load 1 [get_ports pcpi_rs1*]
set_output_delay -clock  clk -min -rise  0.5 [get_ports pcpi_rs2*]
set_output_delay -clock  clk -min -fall  0.5 [get_ports pcpi_rs2*]
set_output_delay -clock  clk -max -rise  1 [get_ports pcpi_rs2*]
set_output_delay -clock  clk -max -fall  1 [get_ports pcpi_rs2*]
set_load 1 [get_ports pcpi_rs2*]
set_output_delay -clock  clk -min -rise  0.5 [get_ports eoi*]
set_output_delay -clock  clk -min -fall  0.5 [get_ports eoi*]
set_output_delay -clock  clk -max -rise  1 [get_ports eoi*]
set_output_delay -clock  clk -max -fall  1 [get_ports eoi*]
set_load 1 [get_ports eoi*]
set_output_delay -clock  clk -min -rise  0.5 [get_ports trace_valid]
set_output_delay -clock  clk -min -fall  0.5 [get_ports trace_valid]
set_output_delay -clock  clk -max -rise  1 [get_ports trace_valid]
set_output_delay -clock  clk -max -fall  1 [get_ports trace_valid]
set_load 1 [get_ports trace_valid]
set_output_delay -clock  clk -min -rise  0.5 [get_ports trace_data*]
set_output_delay -clock  clk -min -fall  0.5 [get_ports trace_data*]
set_output_delay -clock  clk -max -rise  1 [get_ports trace_data*]
set_output_delay -clock  clk -max -fall  1 [get_ports trace_data*]
set_load 1 [get_ports trace_data*]